### PR TITLE
Update ArenaQuickJoin with new APIs to support LoD

### PR DESCRIPTION
**Pull request by iam3yal**
1. Update Active, when called with no args it activates the module.
2. Update Inactive, when called with no args it deactivates the module.
3. Add CanBeActivated to determine whether the module can be activated before calling Active or Inactive.
4. Add IsActivated to determine whether it was activated before.
5. ArenaQuickJoin is Inactive by default.

### CODE REVIEW

**Comment by iam3yal** [comment]
@derfloh205 Yes, well, the button no longer loads the PvP UI and it notifies the player that it should do that once by opening it once.

**Comment by derfloh205** [comment]
@iam3yal Ok so if you are done Ill merge

**Comment by iam3yal** [comment]
@derfloh205 Don't merge just yet I still want to make some changes.

**Comment by derfloh205** [comment]
@iam3yal just write me when I can merge :) (or merge yourself)

**Comment by derfloh205** [comment]
@iam3yal would you mind making future changes within this repo on different branches? Its hard to test when all changes are on your fork

**Comment by iam3yal** [comment]
@derfloh205 Sure.

**Pull request merged**
